seed: 42
data_path: "./pasta_data.csv"
image_size: 224
swin:
  model_name: 'swin_s'
  train_args:
    num_epochs: 1
    batch_size: 8
    lr: 0.0001
    weight_decay: 0.01
    log_interval: 1
    n_splits: 5
