seed: 42
data_path: "./pasta_data.csv"
image_size: 224
n_splits: 5
num_epochs: 3
lr: 0.0001
num_classes: 16
swin:
  model_name: 'swin_s'
  batch_size: 100
  weight_decay: 0.05
  log_interval: 1
  min_batas: 0.9
  max_betas: 0.999
  warmup_epochs: 20
  warmup_start_lr: 0.000001
  output_dir: './swin'
  scheduler: 'OneCycleLR'
  mixup: 0.8
  cutmix: 1.0
maxvit:
  model_name: 'maxvit_t'
  batch_size: 100
  weight_decay: 0.05
  log_interval: 1
  min_batas: 0.9
  max_betas: 0.999
  warmup_epochs: 32
  warmup_start_lr: 0.000001
  output_dir: './maxvit'
  scheduler: 'OneCycleLR'
  mixup: 0.8
  cutmix: 1.0
regnet:
  model_name: 'regnet_y_32gf'
  batch_size: 100
  weight_decay: 0.05
  log_interval: 1
  min_batas: 0.9
  max_betas: 0.999
  warmup_epochs: 32
  warmup_start_lr: 0.000001
  output_dir: './regnet'
  scheduler: 'OneCycleLR'
  mixup: 0.8
  cutmix: 1.0
efficientnetv2:
  model_name: 'efficientnet_v2_m'
  batch_size: 100
  weight_decay: 0.05
  log_interval: 1
  min_batas: 0.9
  max_betas: 0.999
  warmup_epochs: 32
  warmup_start_lr: 0.000001
  output_dir: './efficientnetv2'
  scheduler: 'OneCycleLR'
  mixup: 0.8
  cutmix: 1.0
convnext:
  model_name: 'convnext_large'
  batch_size: 100
  weight_decay: 0.05
  log_interval: 1
  min_batas: 0.9
  max_betas: 0.999
  warmup_epochs: 32
  warmup_start_lr: 0.000001
  output_dir: './convnext'
  scheduler: 'OneCycleLR'
  mixup: 0.8
  cutmix: 1.0


